


---
pagetitle: CV
output:
  html_document:
    fig_width: 1
---

[Download CV as pdf.](files/Tara_Bedi_CV_Website.pdf)

<br>

## Tara Sylvia Bedi CV

#### **Contact Information**<br>
*Address:* 69 Donore Avenue, Dublin 8  <br>
*E-mail:* tbedi@tcd.ie  <br>

**Citizenship:** Ireland & USA 

**Research Focus:** Economic Development, Applied Microeconomics, Household Behaviour, Gender, Social Protection, Well-Being, Social Norms, Financial Inclusion,  Labour Markets, Accountability, Donations

#### **CURRENT EMPLOYMENT** <br>
**University of Dublin, Trinity College (TCD)** <br>
Department of Economics Dublin, Ireland <br>
Research Fellow, Since 2021 <br>
MSCActions Research Fellow, 2017-2020

#### **EDUCATION** <br>
**University of Dublin, Trinity College (TCD)** <br>
Dublin, Ireland <br>
*Ph.D. Development Economics*, 2013 - 2018 <br>

* Dissertation Topic: “Innovative and effective financial services and information awareness for inclusive poverty reduction: The role of mobile banking and awareness programmes in changing saving, credit and employment behaviour of poor households and the resulting impact on household welfare.”
* Advisor: Michael King
* Committee: Andrew McKay, Tara Mitchell

**Harvard Kennedy School of Government**<br>
Cambridge, USA<br>
*Master of Public Administration in International Development*, 2002 - 2004 <br>
Core subjects: Analysing politics for policy, human rights and international politics, good governance and democratisation, legal, social and political institutions in development, resource contes- tation, development policy analysis & design, advanced micro and macro economics, econometrics

**Lewis & Clark College, Economics Department***<br>
Portland, USA*<br>
*BA in Economics with Honours*, 1996 - 2000

#### **PUBLICATIONS**

* Hyperinflation in Zimbabwe: Background, Impact, and Policy. (2019), with T. McIndoe-Calder and R. Mercado. Palgrave Pivot.
* Formal Financial Inclusion in Kenya: Understanding the Demand-Side Constraints. (2015), with M. King. Chapter in Kenya’s Financial Transformation in the 21st Century. Edited by Amrik Heyer and Michael King. Nairobi, Kenya: FSD Kenya
* Leading Edge 2020: Critical Thinking on the Future of International Development. (2011), with M. Bateman, L. Gold and O. Moore. Trócaire.
* My Word is my Bond: Delivery of aid commitments by Ireland. (2010), with B Riordan. Tr\`{o}caire Development Review 2010, 101-22
* More than a pretty picture: using poverty maps to design better policies and interventions. (2007), with A. Coudouel and K. Simler. Washington, DC: World Bank.
* Beyond the numbers: understanding the institutions for monitoring poverty reduction strategies. (2006), with A. Coudouel, M. Cox, M. Goldstein, and N. Thornton. Washington, DC: World Bank.
* Impact Evaluation and the Project Cycle. (2006), with S. Bhatti, X. Gine, E Galasso, M. Goldstein, and A. Legovini.

#### **IN REVIEW**
* Shifting spousal decision-making patterns: Who you target in an agriculture intervention matter. The impact of Farmer’s Innovation Fund in Ethiopia, with N. Buehren, M. Goldstein and T. A. Ketema.

#### **WORKING PAPERS**

* Forty Years of Charitable Giving in Ireland: What have we learnt, with O. B. Breen and J. Carroll.
* Mental Accounting, Spousal Control and Intra-Household Communication: Evidence from an Experiment in India, with A. Jose and M. King
* Accountability of public works entitlements in rural India, with L. Kuld.
* Income Uncertainty and Preferences for Formal Financial Products: Evidence from Rural Kenya, with M. King.

#### **POLICY BRIEFS**
* Achieving social impact through Graduation programmes
* Overview of the Results from the QuIP Report on Concern Worldwide Graduation Programme, Malawi, with Concern Worldwide.
* The Graduation Model and Gender Empowerment Research Project in Malawi, with Concern Worldwide.
* Highlights from the Baseline Survey on the Graduation Households, with Concern Worldwide. 
* The Umodzi Pilot: Successes and Learnings, with Concern Worldwide.

#### **BLOGS**
* Invited podcast guest on [Brand Called You](https://www.youtube.com/watch?v=eyvcEuIqstg)
* Spotlight on Research: [Tara Bedi](https://research.ie/what-we-do/loveirishresearch/blog/spotlight-on-research-tara-bedi/}{Spotlight on Research: Tara Bedi)

#### **TEACHING EXPERIENCE**
**Trinity College Dublin** <br>
Dublin, Ireland

* Module Coordinator & Lecturer, Impact Measurement
<br>Masters in Development Practice, 2018 - 2023
* Lecturer, Survey Design and Qualitative Evaluation Methods, <br>
Trinity IMpact Evaluation (TIME) Online Course on Impact Evaluation, 2021 - 2023
* Supervision of nine master dissertations <br>
Masters in Development Practice, 2021 - 2023
* Teaching Assistant, Microeconomics (2nd year) <br>
Department of Economics, 2016 - 2017
* Lecturer, Economics of Less Developed Countries (3rd year)  <br>
Department of Economics, 2015 - 2016
* Teaching Assistant, Introduction to Economic Policy (1st year) <br>
Department of Economics, 2013 - 2014 

#### **Honours, Awards, Grants**

* Mental Well-Being and School-Related Gender Based Violence: Evidence from Zambia (2023 - 2025), with Wei Chang, Menaal Ebrahim, Anu Jose, Michael King, and Sophia Friedson-Ridenour. Funder: World Bank (\${250,000})
* Gender Norms and the Mauritania Social Transfer Programme (2021 - 2024), with Michael King, Rachael Pierotti and Julia Vaillant. Funder 1: World Bank (\$320,750); Funder 2: International Food Policy Research Institute (IFPRI) (\$125,000)
* Impact Evaluation of Concern’s Graduation Model in Malawi (2017 - 2024), with Michael King. Funder: Concern Worldwide (\€2,150,000)
* Impact of a gender targeted graduation model and norm-transforming intervention on IPV (2020 - 2022), with Michael King and A. Ramos. Funder: Innovations for Poverty Action (IPA) (\$30,183.00)
* Marie Sk\l{}odowska-Curie Actions COFUND Collaborative International Research Fellowship for a Responsive and Innovative Europe (CAROLINE). (2017 - 2022) “Understanding the Gender and Inequality: Dimensions of a Leading Multifaceted Anti-Poverty Programme (the Graduation Model).” Funder: Irish Research Council (\€205,120)
* Government of Ireland Postgraduate Scholarship (2014 - 2017). Funder: Irish Research Council (\€78,000)
* Department Scholarship, Department of Economics (2013 - 2017). Funder: Trinity College Dublin (\€20,000)
* John F. Kennedy Scholarship. (2002 - 2004). Funder: Harvard University (\$20,000)
* Mary Stuart Rogers Scholar (1999). Funder: Lewis & Clark College (\$5,000)

#### **CURRENT RESEARCH PROJECTS**

**RANDOMISED CONTROL TRIALS**

* *Mental Well-Being and School-Related Gender Based Violence, Evidence from Zambia:* Using a randomised control trial (RCT), with randomisation at the school level, this study will evaluate the impact of the empowerment programme on adolescent girls' knowledge of school related gender based violence (SRGBV); attitudes and norms around gender roles, corporal punishment, bullying, sexual violence, and response to SRGBV; socio-emotional skills; mental health and social support. Data will be collected from approximately 3,000 adolescent girls and their teachers/peers/caregivers across three districts in Zambia. Affiliated authors and institutions: Tara Bedi, Wei Chang, Menaal Ebrahim, Anu Jose, Michael King, and Sophia Friedson-Ridenour. Trinity College Dublin, Africa Gender Innovation Lab World Bank.

* *Gender, Social Norms and the Mauritania Social Transfer Programme:* Designed, secured funding and implemented a RCT on understanding the impact of gender social norms interventions. The RCT tests the effect of adding a) couples empowerment training and b) community interventions to a cash transfer programme on female empowerment, spousal cohesion and welfare outcomes. Affiliated authors and institutions: Tara Bedi, Claire Boxho, Michael King and Julia Vaillant. Trinity College Dublin and Africa Gender Innovation Lab World Bank <br>
Research website: https://www.tcd.ie/time/research/social-protection/gender_mauritania/


* *Gender impacts from the Graduation Programme in Malawi:* Designed, secured funding and implemented a randomised control trial (RCT), which studies the impact of varying the gender of the recipient of an anti-poverty programme and a gender empowerment training on intrahousehold bargaining power, well-being, and household poverty. Affiliated authors and institutions: Tara Bedi, Michael King, and Julia Vaillant. Trinity College Dublin, Africa Gender Innovation Lab World Bank.<br>
Research website: https://www.tcd.ie/time/research/malawigraduation/

**LAB EXPERIMENTS**

* *Joint Accounts in the Fintech Era:* We revisit the topic of joint accounts and assess how their terms of labelling, transparency and spousal approval, increasingly varied due to innovations in the fintech sector, affect intrahousehold allocation decisions.  We also assess the impact of personally earning money versus gifted money on subsequent expenditure decisions of couples.  Affiliated authors and institutions: Tara Bedi,  Anu Jose and Michael King. Trinity College Dublin. <br>
Research website: https://www.tcd.ie/time/research/financial/joint-accounts-india/

**MIXED METHODS**

* *Female Empowerment and Well Being:* Designed a mixed methods evaluation that incorporates a qualitative study along side the RCT on the gender focused multifaceted anti-poverty, 'graduation', programme in Malawi. The objective of this research is to enable a deeper understanding of participants' own interpretation of the programme's impact on their empowerment and household relations. The qualitative component involved two rounds of the Qualitative Impact Protocol (QuIP), a method for mapping causal drivers of change from the perspective of female participants, where the qualitative researchers are partially 'blindfolded' to reduce pro-project and confirmation bias. The RCT comprised 'before' and 'after' surveys, separated by 24 months, of both spouses. Affiliated authors and institutions:} Rebekah Avard, Tara Bedi, James Copestake, and Michael King. Trinity College Dublin, University of Bath.

* *Gender Norms and the Mauritania Social Transfer Program:* Designed and secured funding for a qualitative research project on a cash transfer combined with gender norms programming to study 1) the role of complementary programming and the 2) mechanisms underlying the impact of cash transfers on intimate partner violence.The research team will examine the mechanisms of impact and how they vary across different versions of the gender norms programme. This will include investigation of changes at the household level and the possibility of socially transformative changes. The study will use a combination of Qualitative Impact Protocol (QuIP) interviews at the household level, Focus Group Discussions (FDGs) and observational ethnographic research within communities. Affiliated authors and institutions:} Tara Bedi, Claire Boxho, James Copestake, Michael King, Rachael Pierotti, Fiona Remnant and Julia Vaillant. Trinity College Dublin and Africa Gender Innovation Lab World Bank, University of Bath. 

**OTHER PROJECTS**

* *The Donations Project in Ireland:* Designed a research project using the Irish Household Budget Survey, 1987 through 2015, to look at the growth patterns and factors that shifted household donations, including tax policy, over the past four decades. Affiliated authors and institutions: Tara Bedi, Oonagh B. Breen, and James Carroll. Trinity College Dublin and  University College Dublin. 

* *Weather Shocks, Poverty and Well-being in Malawi:*  In this project, we look at the impact of Cyclone Idai in Malawi on household welfare, well-being and gender dynamics. Affiliated authors and institutions: Tara Bedi, Michael King,  Ilan Noy, and Julia Vaillant. Trinity College Dublin, Africa Gender Innovation Lab World Bank and Victoria University of Wellington, New Zealand.

* *The Contrasting Profile of Spousal Mental Well-being In Africa, Evidence from Malawi:* Making use of a detailed panel survey data from Malawi, this research will focus on whether spouses in poor households of rural Malawi differ in their mental health status. Our measures include GAD, self-efficacy, and an index of depression/stress/life satisfaction. The paper will investigate potential correlates, including social norms, that may explain any differentials between the mental health of men and women. Affiliated authors and institutions: Tara Bedi,  Anu Jose and Michael King. Trinity College Dublin. 

* *Impact of Natural Disasters on Mental Well-being and Bandwidth, Evidence from Malawi:* Using a household-level panel survey from Malawi containing a detailed mental well-being module for couples and information related to cyclone Idai and its associated flooding, we investigate the effect of the disaster on the self-efficacy of individuals. As almost all individuals reported being affected by the flood, we define a shock threshold to compare those most severely affected and those less so. To overcome reporting bias in relation to flooding damages, and the possibility that the level of damage might be correlated with unobservables that also affect mental well-being, we combine the household panel data with geospatial data on rainfall and proximity to the nearest river. Contributing to the literature on gender differential effects of disasters and shocks, we estimate the effects of the cyclone by gender. Building on the existing evidence related to the importance of aspirations and efforts in post-disaster recovery, this study analyses spousal self-efficacy post-disaster. Our intrahousehold comparison allows us to examine the gender-specific tools required for mitigating disaster impacts among couples. Affiliated authors and institutions: Tara Bedi,  Michael King and Samuel McArdle. Trinity College Dublin, IGEES.  

* *Exploring Intra-Household Gender Differences in Reporting Exposure to Shocks:* Poor households are more susceptible to face negative shocks, which may undermine development and anti-poverty interventions. Yet, in attempting to understand households' exposure to shocks, it might be imperative to consider the gender of the respondent when utilising survey-based measures. A growing body of literature is exposing intra-household gender differences in survey reporting of various socio-economic measures, even those seemingly objective. This paper contributes by adding a ``shock''dimension to this literature. Using survey data that captures household shock reports by both the male and female spouse within a household in rural Malawi, the paper aims to establish whether men and women report household shocks differently. Moreover, it seeks to explore possible mechanisms that correlate with spousal concordance, and whether concordance can be associated with women's wellbeing outcomes. The results of this paper will make valuable contributions to research using survey-based measures to study household shocks. For instance, if systematic differences are detected, reliance on responses from only one spouse might entail biases which should be carefully considered when targeting, or evaluating the impact of, development interventions based on these measures.  Affiliated authors and institutions: Nouf Abushehab, Tara Bedi, and Michael King. Trinity College Dublin.

#### **WORK EXPERIENCE**

**UNU-WIDER**, Dublin, Ireland <br>
Dublin, Ireland <br>
*Short-term consultant*, 2017 

* Analysed and wrote a chapter on household credit access in Vietnam from the latest round of Vietnam Access to Resources Household Survey (VARHS)

**World Bank**, Dublin, Ireland <br>
*Short-term Consultant*, Summer 2013 

* Co-wrote a research paper looking at the issue of unemployment and social safety nets in Latvia.

**Trócaire**, Maynooth, Ireland <br>
*Policy Officer*, 2011 - 2013 <br>

* Developed and delivered policy and advocacy projects on Financing For Development, including Tax Justice, and Policy Coherence for Development.
* Developed an M&E framework for policy and advocacy and wrote the annual M&E report on policy and advocacy for the organisation.

*Policy & Research Coordinator*, 2008 - 2011

* Managed a team of policy officers and administration support. Responsibilities included setting work agendas for individuals in the team, monitoring progress, and creating opportunities to develop individual skill sets. Additional responsibilities included developing standards on policy publications and establishing monitoring and evaluation processes for advocacy work.
*Lead researcher for the Trócaire Research publication “Leading Edge 2020: Critical thinking on the future of International Development.” Responsibilities included securing funding for the project, developing research methodology and analysis framework, collecting and analysing the data and managing a team of researchers.
* Editor of the Trócaire Development Review, the annual policy journal produced by Trócaire, activities included drafting call for papers, securing papers for journal, overseeing reviewing process, managing relationship with people on the editorial board, producing journal and dissemination of the journal.

*Research Officer on Food Security, Livelihoods & Environmental Justice Team*, 2007 - 2008

* Lead and designed research on food security, developed case studies on successful initiatives of Trócaire‘s food security work, wrote Trócaire‘s contribution to the Irish Government’s Hunger Task Force and regularly briefed Trócaire‘s Director for the Hunger Task Force’ meetings.

***World Bank, Poverty Reduction & Economic Management (PREM)***, Washington DC, USA <br>
*Junior Professional Associate*, 2004 - 2006 <br>
Poverty Analysis, Monitoring & Impact Evaluations team in the Poverty Reduction Group

* Co-managed the work programme on Using Small Area Estimation Poverty Maps to Allocate Resources and Design Policy. Tasks included drafting the concept note, overseeing 14 country studies, managing consultants, providing guidance and feedback on reports, writing papers on poverty map applications and on strengthening the impact of poverty maps, organising a conference on the emerging lessons and the case studies, and making presentations on the results of the work programme
* Coordinated work on Impact Evaluations, including organising workshops, trainings and lunchtime seminars, supervising development of an impact evaluation database. Researched and co-wrote a qualitative evaluations methods note and an evaluation standards best practice review.

***Immigrant and Refugee Community Organisation (IRCO) )***, Portland, USA <br>
*Programme Coordinator of Volunteers*, 2001 - 2002 <br>
Non-profit refugee resettlement service organisation

* Responsible for recruitment, training, support and management of over 100 volunteers at IRCO
* Co-lectured a Portland State University Senior class
* Identified, designed and implemented new volunteer opportunities, such as Youth Mentors, Case Managers for Domestic Violence programme
* Developed outreach programmes between the local community and newly arrived refugees
* Created programme handouts, newsletters, supplemental training and educational material

#### **COMPUTER SKILLS AND LANGUAGES**

* Statistics: Stata (excellent), basic knowledge of R
* Typesetting: LaTex, Microsoft Office
* Languages: English (native), Spanish (intermediate)

#### **BOARD MEMBERSHIP AND CERTIFICATES**

* Master in Development Practice, Course Committee Member, Trinity College Dublin
* Board Director of Plan International Ireland
* Researcher Gathering on Financial Inclusion and Social Protection, 2022 (Chicago); European Research Network On Philanthropy (ERNOP) Conference, 2021 (Dublin); Africa Gender Equal- ity Conference, 2021 (virtual); UN Commission for the Status of Women, 2021 (virtual); the Gen- der Study Group, 2021 (virtual); MenEngage Ubuntu Symposium, 2021 (virtual); RESULTS.org, 2019 (virtual); Irish Aid, 2019 (Malawi); World Bank, 2019 (Washington DC and Malawi); Gates Foundation, 2019 (Seattle); Skoll Ecosystem Session: Poverty Graduation & Women’s Economic Empowerment, 2019 (Oxford); DIAL Development conference, 2017 (Paris); NORDIC conference in Development Economic, 2016 (Oslo).
*  Certificates: Social Norms, Social Change I. Social Norms, Social Change II

#### **CONFERENCES AND INVITED PRESENTATIONS**

*  Re-imagining Social Protection in a time of Global Uncertainty, 2023 (Brighton, upcoming) 
*  Keynote: Disruptive Technologies in Computing and Communication Systems, 2023 (Hyderabad)
*  Researcher Gathering on Financial Inclusion and Social Protection, 2022 (Chicago)
*  Irish Aid, 2021 (Malawi)
*  Graduation Programme Learning Event: Concern Worldwide in collaboration with Ministry of EP\&D, 2021 (Malawi)
*  European Research Network On Philanthropy (ERNOP) Conference, 2021 (Dublin)
*  Africa Gender Equality Conference, 2021 (virtual)
*  UN Commission for the Status of Women, 2021 (virtual)
*  The Gender Study Group, 2021 (virtual)
*  MenEngage Ubuntu Symposium, 2021 (virtual)
*  RESULTS.org, 2019 (virtual)
*  Irish Aid, 2019 (Malawi)
*  World Bank, 2019 (Washington DC and Malawi)
*  Gates Foundation, 2019 (Seattle)
*  Skoll Ecosystem Session: Poverty Graduation \& Women's Economic Empowerment, 2019 (Oxford)
*  DIAL Development conference, 2017 (Paris)
*  NORDIC conference in Development Economic, 2016 (Oslo)

#### **REVIEWING AND EDITORIAL ACTIVITIES**

*  Journal Reviewer: World Development Perspectives; Economic Modelling
*  Funding: Women's Economic Empowerment and Digital Finance (WEE-DiFine) 
*  Editor: Trócaire Development Review, 2008 - 2010
