---
title: "Publications"
output:
  html_document:
    fig_width: 1
---

<br>

### Peer-reviewed book

- Hyperination in Zimbabwe: Background, Impact, and Policy,
_Palgrave Pivot_ (2019), with T. McIndoe-Calder and R. Mercado.

### R \& R
- Accountability of public works entitlements in rural India, with L. Kuld.
- Forty Years of Charitable Giving in Ireland: What have we learnt, with  O. B. Breen and J. Carroll.

### Publications
- Formal Financial Inclusion in Kenya: Understanding the Demand-Side Constraints. (2015), with M. King. Chapter in Kenya's Financial Transformation in the 21st Century.} Edited by Amrik Heyer and Michael King. Nairobi, Kenya: FSD Kenya
- Leading Edge 2020: Critical Thinking on the Future of International Development. (2011), with M. Bateman, L. Gold and O. Moore. Trócaire.
- My Word is my Bond: Delivery of aid commitments by Ireland. (2010), with B Riordan. Trócaire Development Review 2010, 101-22
- More than a pretty picture: using poverty maps to design better policies and interventions. (2007), with A. Coudouel and K. Simler. Washington, DC: World Bank.
- Beyond the numbers: understanding the institutions for monitoring poverty reduction strategies. (2006), with A. Coudouel, M. Cox, M. Goldstein, and N. Thornton. Washington, DC: World Bank.
- Impact Evaluation and the Project Cycle. (2006), with S. Bhatti, X. Gine, E Galasso, M. Goldstein, and A. Legovini.   


### Working Papers
- Mental Accounting, Spousal Control and Intra-Household Communication: Evidence from an Experiment in India, with A. Jose and M. King
 - Shifting spousal decision-making patterns: Who you target in an agriculture intervention matter. The impact of Farmer's Innovation Fund in Ethiopia (2022), with N. Buehren, M. Goldstein and T. A. Ketema
- Income Uncertainty and Preferences for Formal Financial Products: Evidence from Rural Kenya, with M. King.

### Papers in Progress
- Natural Disasters, Mental Health and the Ultra-poor: Intra-household Impacts of Cyclone Idai in Malawi, with A. Jose, M. King, S. McArdle
- Developing an Evaluation Framework for Gender-responsive Climate Change Adaptation Programme: from Design to Impact, with X. Zhao
- Ultra-Poor Graduation and Environmental Shocks: Evidence from the 2019 Malawian Floods, with M. King and I. Noy
- Gender Targeting and Household Cooperation: Experimental Evidence from a Multifaceted Anti-poverty Program in Malawi, with M. King and J. Vaillant
- Income Uncertainty and Preferences for Formal Financial Products: Evidence from Rural Kenya, with M. King.
- Moving the Female Empowerment Needle: A Mixed-Method Evaluation of A Gender Focused Multifaceted Anti-Poverty Programme in Malawi, with R. Avard, J. Copestake, M. King and F. Remnant.
- A mixed method approach to understanding Gender Social Norms, IPV and the Mauritania Social Transfer Program, with C. Boxho, M. King, R. Pierotti and J. Vaillant.
- Bargaining, Poverty Stress, or Backlash? Reducing Violence Among the Ultra-Poor, with M. King, A. Ramos, and J. Vaillant.

### Policy Briefs
-  Achieving social impact through Graduation programmes
- Overview of the Results from the QuIP Report on Concern Worldwide Graduation Programme, Malawi, with Concern Worldwide.
- The Graduation Model and Gender Empowerment Research Project in Malawi, with Concern Worldwide.
-  Highlights from the Baseline Survey on the Graduation Households, with Concern Worldwide. 
- The Umodzi Pilot: Successes and Learnings, with Concern Worldwide.

### Blog posts
- [Brand Called You](https://www.youtube.com/watch?v=eyvcEuIqstg)
- [Spotlight on Research: Tara Bedi](https://research.ie/what-we-do/loveirishresearch/blog/spotlight-on-research-tara-bedi/)






