---
title: "Research projects"
output:
  html_document:
    fig_width: 1
---


### Gender impacts from the Graduation Programme in Malawi:
Research website:  https://www.tcd.ie/time/research/malawigraduation/

Designed, secured funding and implemented a four arm (three treatments and one control) randomised control trial (RCT) from a pool of 3,200 eligible poor married households in rural Malawi. The research studies the impact of varying the gender of the recipient of an anti-poverty programme (the Graduation program) and a gender empowerment training on intrahousehold bargaining power, well-being, and household poverty. Affiliated authors and institutions: Tara Bedi, Michael King, and Julia Vaillant. Trinity College Dublin, Africa Gender Innovation Lab World Bank.




<br>

### Female Empowerment, Well Being and Marriage Quality: A Mixed-Method Evaluation of A Gender Focused Multifaceted Anti-Poverty Programme in Malawi

Designed a mixed methods evaluation that incorporates a qualitative study along side the RCT on the gender focused multifaceted anti-poverty, ‘graduation’, program in Malawi. The objective of this research is to enable a deeper understanding of participants’ own interpretation of the programme’s impact on their empowerment and household relations. The qualitative component involved two rounds of the Qualitative Impact Protocol (QuIP), a method for mapping causal drivers of change from the perspective of female participants, where the qualitative researchers are partially ‘blindfolded’ to reduce pro-project and confirmation bias. The RCT comprised ‘before’ and ‘after’ surveys, separated by 24 months, of both spouses. Affiliated authors and institutions: Rebekah Avard, Tara Bedi, James Copestake, and Michael King. Trinity College Dublin, University of Bath.




<br>

### Gender, Social Norms and the Mauritania Social Transfer Programme:
Research Website: https://www.tcd.ie/time/research/social-protection/gender_mauritania/

Designed, secured funding and implemented a RCT on understanding the impact of gender social norms interventions. The RCT tests the effect of adding a) couples empowerment training and b) community interventions to a cash transfer programme on female empowerment, spousal cohesion and welfare outcomes. Affiliated authors and institutions: Tara Bedi, Claire Boxho, Michael King and Julia Vaillant. Trinity College Dublin and Africa Gender Innovation Lab World Bank 

<br>

###  Gender Norms and the Mauritania Social Transfer Program:
Designed and secured funding for a qualitative research project on a cash transfer combined with gender norms programming to study 1) the role of complementary programming and the 2) mechanisms underlying the impact of cash transfers on intimate partner violence.The research team will examine the mechanisms of impact and how they vary across different versions of the gender norms programme. This will include investigation of changes at the household level and the possibility of socially transformative changes (Molyneux et al. 2016). The study will use a combination of Qualitative Impact Protocol (QuIP) interviews at the household level, Focus Group Discussions (FDGs) and observational ethnographic research within communities. Affiliated authors and institutions: Tara Bedi, Claire Boxho, James Copestake, Michael King, Rachael Pierotti, Fiona Remnant and Julia Vaillant. Trinity College Dublin and Africa Gender Innovation Lab World Bank, University of Bath.



### Joint Accounts in the Fintech Era:
Research website: https://www.tcd.ie/time/research/financial/joint-accounts-india/ 

In a lab experiment setting, we revisit the topic of joint accounts and assess how their terms of labelling, transparency and spousal approval, increasingly varied due to innovations in the fintech sector, affect intrahousehold allocation decisions. We also assess the impact of personally earning money versus gifted money on subsequent expenditure decisions of couples.  Affiliated authors and institutions: Tara Bedi, Anu Jose and Michael King. Trinity College Dublin.  


<br>

### The Donations Project in Ireland:

Designed a research project using the Irish Household Budget Survey, 1987 through 2015, to look at the growth patterns and factors that shifted household donations, including tax policy, over the past four decades. Affiliated authors and institutions: Tara Bedi, Oonagh B. Breen, and James Carroll. Trinity College Dublin and  University College Dublin.

<br>

### Weather Shocks, Poverty and Well-being:

In this project, we look at the impact of Cyclone Idai in Malawi on household welfare, well-being and gender dynamics. Affiliated authors and institutions: Tara Bedi, Michael King, Ilan Noy, and Julia Vaillant. Trinity College Dublin, Africa Gender Innovation Lab World Bank and Victoria University of Wellington, New Zealand. 

<br>

### The Gender Differential Impacts of Weather Shocks on Well-being:

Using a household-level panel survey from Malawi containing a detailed mental well-being module for couples and information related to cyclone Idai and its associated flooding, we investigate the effect of the disaster on the self-efficacy of individuals. As almost all individuals reported being affected by the flood, we define a shock threshold to compare those most severely affected and those less so. To overcome reporting bias in relation to flooding damages, and the possibility that the level of damage might be correlated with unobservables that also affect mental well-being, we will combine the household panel data with geospatial data on rainfall and proximity to the nearest river. Contributing to the literature on gender differential effects of disasters and shocks, we estimate the effects of the cyclone by gender. Building on the existing evidence related to the importance of aspirations and efforts in post-disaster recovery, this study analyses spousal self-efficacy post-disaster. Our intrahousehold comparison allows us to examine the gender-specific tools required for mitigating disaster impacts among couples. Affiliated authors and institutions: Tara Bedi, Samuel McArdle and Michael King. Trinity College Dublin. 

<br>

### Exploring Intra-Household Gender Differences in Reporting Exposure to Shocks 
Poor households are more susceptible to face negative shocks, which may undermine development and anti-poverty interventions. Yet, in attempting to understand households’ exposure to shocks, it might be imperative to consider the gender of the respondent when utilizing survey-based measures. A growing body of literature is exposing intra-household gender differences in survey reporting of various socio-economic measures, even those seemingly objective. This paper contributes by adding a “shocks” dimension to this literature. Using survey data that captures household shock reports by both the male and female spouse within a household in rural Malawi, the paper aims to establish whether men and women report household shocks differently. Moreover, it seeks to explore possible mechanisms that correlate with spousal concordance, and whether concordance can be associated with women’s wellbeing outcomes. Finally, it aims to evaluate whether a randomised couple’s empowerment training impacts spousal concordance in reporting household shocks. The results of this paper will inform valuable considerations for research using survey-based measures to study household shocks. For instance, if systematic differences are detected, reliance on responses from only one spouse might entail biases which should be carefully considered when targeting, or evaluating the impact of, development interventions based on these measures.  Affiliated authors and institutions: Nouf Abushehab, Tara Bedi, and Michael King. Trinity College Dublin. 

<br>

### The Contrasting Profile of Spousal Mental Well-being In Africa, Evidence from Malawi:
Making use of a detailed panel survey data from Malawi, this research will focus on whether spouses in poor households of rural Malawi differ in their mental health status. Our measures include GAD, self-efficacy, and an index of depression/stress/life satisfaction. The paper will investigate potential correlates, including social norms, that may explain any differentials between the mental health of men and women. Affiliated authors and institutions:} Tara Bedi,  Anu Jose and Michael King. Trinity College Dublin.

<br>
