---
title: "Teaching"
output:
  html_document:
    fig_width: 1
---

<br>

### Current & past classes

<br>


**Trinity College Dublin** <br>
- Module Coordinator & Lecturer: Theories of Development 2023-2025, Masters in Development Practice <br> 
- Module Coordinator & Lecturer: Dissertation \& Work Placement 2023-2025, Masters in Development Practice  <br> 
- Module Coordinator & Lecturer: Gender \& Development 2023-2025, Masters in Development Practice  <br>
- Module Coordinator & Lecturer: Impact Measurement 2018 - 2025, Masters in Development Practice <br>
- Lecturer: Survey Design and Qualitative Evaluation Methods, 2021-2024, Trinity IMpact Evaluation (TIME) Online Course on Impact Evaluation <br>
- Supervision of sixteen master dissertations, 2021-2024, Masters in Development Practice <br>
- Teaching Assistant: Microeconomics (2nd year), 2016  - 2017, Department of Economics <br>
- Lecturer: Economics of Less Developed Countries (3rd year), 2015  - 2016, Department of Economics <br>
- Teaching Assistant: Introduction to Economic Policy (1st year), 2013  - 2014, Department of Economics <br>